### ISSUE TITLE
could you please provide details on the environment used in the project? 

### ISSUE THREAD

**Issue by benayat** [saraansh1999/global-plus-local-fp-transformer#3]
to reproduce results for embeddings, could you please provide more detailed environment specifics? for example, Conda version, python version, and if it's not too much, requirements.txt for pip.

**Comment by saraansh1999** [comment]
Kindly refer to the https://github.com/saraansh1999/global-plus-local-fp-transformer?tab=readme-ov-file#setup section.
Thanks.
